### ISSUE TITLE
end to end traing  is stuck on 'Calculating gradients wrt hypotheses' stage

### ISSUE THREAD

**Issue by SeanGuo063** [vislearn/ngdsac_camreloc#2]
Hi, 
Thank you for your great work. 

I tried to tran the NG-DSAC++ on these four Cambridge Landmark dataset. The first two stages for initializing worked well and I tested the trained model and got good results. However, when I try to train it end-to-end following the instruction, it often get stuck on 'Calculating gradients wrt hypotheses' stage and does not move on. I check the cpu-util, it shows the progress is working, and for gpu-util, it is zero. 

Have you encountered such situation during your training and do you have any suggestions?

Thank you very much.

**Comment by ebrach** [comment]
Hi,

sorry, not sure why this would happen. Can you narrow down which part of the code gets struck? Have you tried to run the test script with the models you trained so far (from the first two stages)? Do they work?

Best,
Eric
