### ISSUE TITLE
Inquires about installation of ngdasc

### ISSUE THREAD

**Issue by Magicboomliu** [vislearn/ngdsac_camreloc#3]
Thank you for your wonderfull work.

I have a inquire about the installation of `ngdasc` module.  

I have opencv-python library directly using `pip install` , not using cmake and complie from the source code.   

So I do not have the headers and libraries folder in cpp. So I have problems setting the opencv path in `setup.py`.   And I trarin in colab, no conda env either.

Should I compile the opencv from source code  or there are other solutions? Thanks your your help.

**Comment by ebrach** [comment]
I think, as you say, opencv-python will not work since you need the headers and libraries for compiling the C++ NGDSAC module. I have no experience with colab and how to install OpenCV there most conveniently. Compiling from source should work in any case if that is possible.

**Comment by Magicboomliu** [comment]
Thank you for you reply. I used Cmake to compile opencv from source code and edit the path in setup.py and finally it works. Thanks for your guidance.
