### ISSUE TITLE
Question when importing ngdsac

### ISSUE THREAD

**Issue by Satuki717** [vislearn/ngdsac_camreloc#4]
Hello, thank you for your wonderful work.

I would like to use your ngdsac module, but I am new to this, and I found a problem in training e2e stage.
It tells me 'ImportError: /home/user/anaconda3/envs/ngdsac/lib/python3.8/site-packages/ngdsac-0.0.0-py3.8-linux-x86_64.egg/ngdsac.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2cv3MatC2Ev'

Although I searched it on Internet, I cannot figure out which part is wrong.
So would you mind giving me some hints about this problem?

**Comment by ebrach** [comment]
That error might indicate compiler compatibility issues. I.e. the compiler on your system is incompatible with the compiler that compiled OpenCV - presumably you installed pre-compiled packages, e.g. via Conda? Either, 
- you find out which compiler OpenCV was compiled with, and use the same compiler version when compiling NG-DSAC or
- you compile OpenCV from source on your system and point the setup.py to that OpenCV version

**Comment by ebrach** [comment]
Possibly related issue: https://github.com/vislearn/ngransac/issues/20
